<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Aitive.Framework.DependencyInjection\Aitive.Framework.DependencyInjection.csproj" />
    <ProjectReference Include="..\Aitive.Framework\Aitive.Framework.csproj" />
    <ProjectReference
      Include="..\Aitive.Framework.SourceGenerators\Aitive.Framework.SourceGenerators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
